/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : bigint,
}
export interface BlockedBuyer {
  'id' : bigint,
  'blockedAt' : bigint,
  'email' : string,
  'reason' : string,
}
export interface PolicyDocument {
  'id' : bigint,
  'fileName' : string,
  'blobId' : string,
  'docType' : string,
  'uploadedAt' : bigint,
}
export interface Review {
  'id' : bigint,
  'templateId' : bigint,
  'createdAt' : bigint,
  'reviewerName' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface Template {
  'id' : bigint,
  'features' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'previewImageBlobId' : string,
  'isFree' : boolean,
  'templateFileBlobId' : string,
  'price' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type OrderStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Order {
  'id' : bigint,
  'templateId' : bigint,
  'transactionRef' : string,
  'screenshotBlobId' : string,
  'buyerName' : string,
  'buyerEmail' : string,
  'buyerMobile' : string,
  'buyerAddress' : string,
  'businessDetails' : string,
  'accountRecovery' : boolean,
  'templateUseCase' : string,
  'status' : OrderStatus,
  'createdAt' : bigint,
}
export interface CountryCount {
  'country' : string,
  'count' : bigint,
}
export interface PaymentSummary {
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'approvedOrders' : bigint,
  'rejectedOrders' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[string, string, boolean], bigint>,
  'addPolicyDocument' : ActorMethod<[string, string, string], bigint>,
  'addReview' : ActorMethod<[bigint, string, bigint, string], bigint>,
  'addTemplate' : ActorMethod<
    [string, string, bigint, boolean, string, string, Array<string>],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockBuyer' : ActorMethod<[string, string], bigint>,
  'deleteAnnouncement' : ActorMethod<[bigint], boolean>,
  'deletePolicyDocument' : ActorMethod<[bigint], boolean>,
  'deleteReview' : ActorMethod<[bigint], boolean>,
  'deleteTemplate' : ActorMethod<[bigint], boolean>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getBlockedBuyers' : ActorMethod<[], Array<BlockedBuyer>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFreeTemplates' : ActorMethod<[], Array<Template>>,
  'getPolicyDocuments' : ActorMethod<[], Array<PolicyDocument>>,
  'getReviews' : ActorMethod<[bigint], Array<Review>>,
  'getTemplateFileId' : ActorMethod<[bigint, string], [] | [string]>,
  'getTemplates' : ActorMethod<[], Array<Template>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmailBlocked' : ActorMethod<[string], boolean>,
  'recordPayment' : ActorMethod<
    [bigint, string, string, string, string, string, boolean, string],
    boolean
  >,
  'unblockBuyer' : ActorMethod<[bigint], boolean>,
  'updateAnnouncement' : ActorMethod<[Announcement], boolean>,
  'updateTemplate' : ActorMethod<
    [bigint, string, string, bigint, boolean, Array<string>],
    boolean
  >,
  'submitOrder' : ActorMethod<
    [bigint, string, string, string, string, string, string, string, boolean, string],
    bigint
  >,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'approveOrder' : ActorMethod<[bigint], boolean>,
  'rejectOrder' : ActorMethod<[bigint], boolean>,
  'getOrdersByEmail' : ActorMethod<[string], Array<Order>>,
  'getApprovedOrderFileId' : ActorMethod<[bigint], [] | [string]>,
  'recordPageVisit' : ActorMethod<[string], undefined>,
  'getPageVisitCount' : ActorMethod<[], bigint>,
  'getVisitorCountries' : ActorMethod<[], Array<CountryCount>>,
  'getPaymentSummary' : ActorMethod<[], PaymentSummary>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
