/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'templateId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : IDL.Int,
});
export const BlockedBuyer = IDL.Record({
  'id' : IDL.Nat,
  'blockedAt' : IDL.Int,
  'email' : IDL.Text,
  'reason' : IDL.Text,
});
export const Template = IDL.Record({
  'id' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'previewImageBlobId' : IDL.Text,
  'isFree' : IDL.Bool,
  'templateFileBlobId' : IDL.Text,
  'price' : IDL.Nat,
});
export const PolicyDocument = IDL.Record({
  'id' : IDL.Nat,
  'fileName' : IDL.Text,
  'blobId' : IDL.Text,
  'docType' : IDL.Text,
  'uploadedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
  'addPolicyDocument' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addReview' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addTemplate' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockBuyer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePolicyDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getBlockedBuyers' : IDL.Func([], [IDL.Vec(BlockedBuyer)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFreeTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'getPolicyDocuments' : IDL.Func([], [IDL.Vec(PolicyDocument)], ['query']),
  'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getTemplateFileId' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmailBlocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'recordPayment' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'unblockBuyer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateAnnouncement' : IDL.Func([Announcement], [IDL.Bool], []),
  'updateTemplate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Vec(IDL.Text)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'templateId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : IDL.Int,
  });
  const BlockedBuyer = IDL.Record({
    'id' : IDL.Nat,
    'blockedAt' : IDL.Int,
    'email' : IDL.Text,
    'reason' : IDL.Text,
  });
  const Template = IDL.Record({
    'id' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'previewImageBlobId' : IDL.Text,
    'isFree' : IDL.Bool,
    'templateFileBlobId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const PolicyDocument = IDL.Record({
    'id' : IDL.Nat,
    'fileName' : IDL.Text,
    'blobId' : IDL.Text,
    'docType' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [IDL.Nat], []),
    'addPolicyDocument' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addReview' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTemplate' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockBuyer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePolicyDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getBlockedBuyers' : IDL.Func([], [IDL.Vec(BlockedBuyer)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFreeTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'getPolicyDocuments' : IDL.Func([], [IDL.Vec(PolicyDocument)], ['query']),
    'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getTemplateFileId' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmailBlocked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'recordPayment' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'unblockBuyer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateAnnouncement' : IDL.Func([Announcement], [IDL.Bool], []),
    'updateTemplate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Vec(IDL.Text)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };